# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("charge_stations_aspe works properly and show error if needed", {
  dpt<-c("44")
liste_stations<-charge_stations_aspe(dpt, code_agence = c("04"))
  expect_true(nrow(liste_stations)>0)
})


