# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("split_observations_aspe works properly and show error if needed", {
  obs<-charge_observations_aspe(code_operation=c("89771","89805"))
detail<-split_observations_aspe(obs)
  expect_true(nrow(detail$detail_operation)>=2)
expect_true(nrow(detail$liste_taxons)>=100)
})


