# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("liste_operations_aspe works properly and show error if needed", {
 dpt<-c("53")
liste_stations<-charge_stations_aspe(dpt, code_agence = c("04"))
liste_stations<-liste_stations[!is.na(liste_stations$code_station),]
liste_op<-liste_operations_aspe(codes_stations=head(liste_stations$code_station,10), 
                      date_debut=as.Date("2010-01-01"), 
                      date_fin=as.Date("2024-01-01"))
  expect_true(nrow(liste_op)>0)
})


