# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("charge_observations_aspe works properly and show error if needed", {
  expect_true(nrow(charge_observations_aspe(code_operation=c("89771")))>0)
})


