# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' charge_observations_aspe
#'
#' @param code_operation Vecteur avec les codes opérations à charger (paramètre obligatoire)
#'
#' @return
#' Liste des stations ciblées
#' @export
#'
#' @examples
#'
#' obs<-charge_observations_aspe(code_operation=c("89771","89805"))
#'
charge_observations_aspe <- function(code_operation) {
  # URL de base de l'API
  base_url <- "https://hubeau.eaufrance.fr/api/v1/etat_piscicole/observations.csv"
  
  # Vérification et formatage des paramètres
  if (!is.null(code_operation)) {
    if (!is.character(code_operation)) {
      stop("code_operation doit être un vecteur de caractères.")
    }
    code_operation <- paste(code_operation, sep = "", collapse = ",")
  } else {
    stop("code_operation doit être non NULL.")
  }
  
  # Paramètres de base de la requête
  params <- list(
    code_operation = code_operation,
    size = 100  # Taille de la page (nombre de résultats par requête)
  )
  
  # Initialiser les variables pour la pagination
  all_stations <- list() # Liste pour stocker toutes les stations
  page <- 1              # Commencer à la première page
  more_data <- TRUE      # Flag pour indiquer s'il y a encore des données à récupérer
  
  # Boucle pour récupérer toutes les pages de résultats
  while (more_data) {
    # Ajouter le paramètre de pagination à la requête
    params$page <- page
    
    # Faire une requête GET à l'API
    response <- httr::GET(url = base_url, query = params)
    
    # Vérifier le code de statut
    if (httr::status_code(response) %in% c(200, 206)) {
      # Obtenir le contenu de la réponse
      content_text <- httr::content(response, as = "text", encoding = "UTF-8")
      
      # Vérifier si le contenu est vide
      if (nchar(content_text) == 0) {
        more_data <- FALSE  # Arrêter la pagination s'il n'y a plus de données
      } else {
        # Lire le contenu CSV de la réponse avec ; comme séparateur
        stations_data <- read.csv2(text = content_text, sep = ";")
        
        # Vérifier si des données sont présentes
        if (!is.null(stations_data) && nrow(stations_data) > 0) {
          # Ajouter ce data.frame à la liste totale
          all_stations <- c(all_stations, list(stations_data))
          
          # Afficher une information de progression
          message(paste("Page", page, "récupérée. Nombre d'enregistrements:", nrow(stations_data)))
          
          # Passer à la page suivante
          page <- page + 1
        } else {
          # Arrêter la pagination si le data.frame est vide
          more_data <- FALSE
        }
      }
    } else {
      # Afficher un message d'erreur si la requête a échoué
      stop(paste("Erreur:", httr::status_code(response)))
    }
  }
  
  # Convertir la liste de stations en data.frame pour analyse ou export
  if (length(all_stations) > 0) {
    stations_df <- do.call(rbind, lapply(all_stations, as.data.frame))
    stations_df <- unique(stations_df)
  } else {
    stations_df <- data.frame()  # Retourne un data.frame vide si aucune donnée n'est récupérée
  }
  
  return(stations_df)
}

