# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' charge_stations_aspe
#'
#' @param dpt Vecteur avec les départements à charger
#' @param code_agence Vecteur avec les codes agences selon https://id.eaufrance.fr/nsa/447
#'
#' @return
#' Liste des stations ciblées
#' @export
#'
#' @examples
#'
#' dpt<-c("44", "56", "22", "35", "49", "53")
#' liste_stations<-charge_stations_aspe(dpt, code_agence = c("04"))
#'
#'
charge_stations_aspe <- function(dpt, code_agence = c("04")) {

# URL de base de l'API
base_url <- "https://hubeau.eaufrance.fr/api/v1/etat_piscicole/stations"

dpt0<-paste(dpt, sep="", collapse = ",")
code_bassin0<-paste(code_agence, sep="", collapse = ",")

# Paramètres de base de la requête
params <- list(
  code_departement = dpt0, # Codes INSEE des départements
  code_bassin = code_bassin0,                    # Code du bassin
  format = "json",                       # Format de la réponse
  size = 100,                             # Taille de la page (nombre de résultats par requête)
fields = "code_station,libelle_station,coordonnee_x_station,coordonnee_y_station,code_point_prelevement_aspe,code_point_prelevement"
  )

# Initialiser les variables pour la pagination
all_stations <- list() # Liste pour stocker toutes les stations
page <- 1              # Commencer à la première page
total_results <- Inf   # Nombre total de résultats à récupérer, infini pour commencer

# Boucle pour récupérer toutes les pages de résultats
while ((page - 1) * params$size < total_results) {
  # Ajouter le paramètre de pagination à la requête
  params$page <- page
  
  # Faire une requête GET à l'API
  response <- httr::GET(url = base_url, query = params)
  
  # Vérifier le code de statut
  if (httr::status_code(response) %in% c(200, 206)) {
    # Convertir le contenu JSON de la réponse en liste R
    stations_data <- jsonlite::fromJSON(httr::content(response, as = "text", encoding = "UTF-8"))
    
   # Vérifier si des données sont présentes
    if (!is.null(stations_data$data) && length(stations_data$data) > 0) {
      # Convertir les données en un data.frame
      stations_df <- as.data.frame(stations_data$data)
      
      # Ajouter ce data.frame à la liste totale
      all_stations <- c(all_stations, list(stations_df))
    }    
    # Mettre à jour le nombre total de résultats si disponible
    if (!is.null(stations_data$count)) {
      total_results <- stations_data$count
    } else {
      # Si l'info de total est absente, on suppose qu'on a tout après la première réponse 200 sans nouvelle data
      break
    }
    
    # Afficher une information de progression
    message(paste("Page", page, "de", ceiling(total_results / params$size), "récupérée."))
    
    # Passer à la page suivante
    page <- page + 1
  } else {
    # Afficher un message d'erreur si la requête a échoué
    stop(paste("Erreur:", httr::status_code(response)))
  }
}

# Convertir la liste de stations en data.frame pour analyse ou export
stations_df <- do.call(rbind, lapply(all_stations, as.data.frame))
return(stations_df)
}
