# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' split_observations_aspe
#'
#' @param observations Résultat renvoyé par la fonction charge_observations_aspe
#'
#' @return
#' Liste avec d'un côté les conditions de l'opération et de l'autre les listes faunistiques
#' @export
#'
#' @examples
#'
#' obs<-charge_observations_aspe(code_operation=c("89771","89805"))
#' detail<-split_observations_aspe(obs)
#'
#'
split_observations_aspe <- function(observations) {

  detail_operation<-unique(observations[,                                 c("code_operation","codes_dispositifs_collecte","libelles_dispositifs_collecte","protocole_peche","objectifs_operation","code_prelevement_elementaire","type_prelevement_elementaire","duree_prelevement_elementaire","numero_passage","type_points","nombre_points","nombre_points_sans_poisson","nombre_points_facies_courant","nombre_points_facies_plat","nombre_points_facies_profond","nombre_points_annexes","nombre_points_berge","nombre_points_chenal","nom_ambiance","longueur_ambiance","largeur_ambiance","profondeur_ambiance","code_facies_ambiance","libelle_facies_ambiance","situation_ambiance","localisation_ambiance","classe_vitesse_courant_ambiance","code_ombrage_ambiance","libelle_ombrage_ambiance","code_granulo_ambiance_dominante","libelle_granulo_ambiance_dominante","code_granulo_ambiance_accessoire","libelle_granulo_ambiance_accessoire","vegetation_ambiance","abondance_cache_vegetation_aquatique_ambiance","abondance_cache_embacles_ambiance","abondance_cache_vegetation_bordure_ambiance","abondance_cache_sous_berge_ambiance","abondance_cache_granulo_ambiance")])
                          
      liste_taxons<-unique(observations[,                                 c("code_operation","code_lot","code_type_lot","libelle_type_lot","effectif_lot","code_taxon","code_alternatif_taxon","nom_commun_taxon","nom_latin_taxon","uri_taxon","taille_min_lot","taille_max_lot","type_longueur_lot","poids_lot_mesure","poids_lot_estime","methode_estimation_poids_lot","code_individu","taille_individu","type_longueur_individu","mesure_individu_reelle","poids_individu_mesure","poids_individu_estime","methode_estimation_poids_individu","sexe_individu","age_individu","codes_pathologies_lot","libelles_pathologies_lot","codes_fractions_pathologies_lot","libelles_fractions_pathologies_lot","uris_fractions_pathologies_lot","importances_pathologies_lot","codes_pathologies_individu","libelles_pathologies_individu","codes_fractions_pathologies_individu","libelles_fractions_pathologies_individu","uris_fractions_pathologies_individu","importances_pathologies_individu")])
  
  return(list(detail_operation=detail_operation,
         liste_taxons=liste_taxons))
}

